In [2]:
import numpy as np

In [8]:
# create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [11]:
#reshape is used to increase dimension
#1D to 2D means it increases of [[]] means dimension
arr2=np.array((1,2,3,4,5))
arr2.reshape(1,5) # 1 rows 5 columns 



array([[1, 2, 3, 4, 5]])

In [13]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [15]:
#2D Array
arr2=np.array([[1,2,3,4,5],[6,7,8,9,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [6 7 8 9 6]]
(2, 5)


In [17]:
#means last element will divides i.e 2
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
# identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# Attrbutes
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)  #Output:(2,3)
print("Number of dimensions:",arr.ndim) #Output:2
print("Size (number of elements):",arr.size) #Output:6
print("Data Type:",arr.dtype) #Output:int 32
print("Item Size(in bytes):",arr.itemsize)  # Output:8 

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data Type: int32
Item Size(in bytes): 4


In [27]:
# Numpy Vectorized Operation 
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

# Element Wise Addition
print("Addition",arr1+arr2)

# Element Wise Substraction
print("Substraction",arr1-arr2)

# Element Wise Multiplication
print("Multiplication",arr1*arr2)

# Element Wise Division
print("Division",arr1/arr2)

Addition [11 22 33 44 55]
Substraction [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]
Division [0.1 0.1 0.1 0.1 0.1]


In [29]:
# Universal Function  
arr=np.array([2,3,4,5])
# Square root
print(np.sqrt(arr))

# Exponential Function
print(np.exp(arr))

#Sine
print(np.sin(arr))

#natural log
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798]
[  7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.69314718 1.09861229 1.38629436 1.60943791]


In [32]:
# array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
print(arr[1,1:3])

[6 7]


In [40]:
# Modify the array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [41]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [45]:
### statistical concepts--Norma1ization
##to have a mean Of 0 and standard deviation Of 1
data = np.array([1,5,3,4,5])
# Calculate the mean and standard deviation
mean= np.mean(data)
std_dev = np. std(data)
# Normalize the data
normalized_data=(data - mean) /std_dev
print( "Normalized data:",normalized_data)
# Output:
# Normalized data:


Normalized data: [-1.73719807  0.93541435 -0.40089186  0.26726124  0.93541435]


In [49]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean=np.mean(data)
print("Mean:",mean)

# Median
median = np.median(data)
print( "Median:" ,median)
# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:",std_dev)
# Variance
variance = np.var(data)
print( "Variance: " ,variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance:  8.25


In [51]:
# Logical Operation 
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5)]

data[(data>=5)&(data<=8)]

array([5, 6, 7, 8])